[project]
name = "confetti"
version = "0.1.0"
description = "A multi-objective counterfactual explanation method for deep learning based multivariate time series classification. This branch contains the complete code used to reproduce all experiments and figures for the CONFETTI paper accepted at AAAI 2026."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "pandas",
    "joblib",
    "keras",
    "scikit-learn",
    "tslearn",
    "matplotlib",
    "sktime",
    "pymoo>=0.6.1.3",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv.sources]
critdd = { git = "https://github.com/mirkobunse/critdd" }

[dependency-groups]

# Development tools only
dev = [
    "ruff>=0.14.1",
    "ty>=0.0.1a25",
]

# Dependencies needed to reproduce the paper experiments
paper = [
    "critdd",
    "pingouin",
    "scikit-posthocs",
    "tsinterpret",
    "tensorflow",
    "notebook",
    "xlsxwriter",
    "tinycss2",
    "dtaidistance",
    "jsonpointer",
    "fqdn",
    "isoduration",
    "uri-template",
    "webcolors",
]
