[project]
name = "confetti"
version = "0.1.0"
description = "A multi-objective counterfactual explanation method for deep learning based multivariate time series."
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "numpy>=1.26",
    "pandas>=2.0",
    "joblib>=1.2",
    "keras>=3.0",
    "scikit-learn>=1.3",
    "pymoo>=0.6.1",
    "tslearn>=0.6",
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "ruff>=0.14.1",
    "ty>=0.0.1a25",
    "sphinx",
    "furo"
]

plots = [
    "matplotlib>=3.8",
]
