[project]
name = "confetti"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dtaidistance==2.3.13",
    "fqdn==1.5.1",
    "isoduration==20.11.0",
    "jsonpointer==3.0.0",
    "keras==3.8.0",
    "notebook==7.3.2",
    "numpy==1.26.4",
    "pandas==2.2.3",
    "pingouin==0.5.5",
    "pip==23.2.1",
    "pymoo==0.6.1.3",
    "scikit-posthocs==0.11.4",
    "tensorflow==2.18.0",
    "tinycss2==1.4.0",
    "tsinterpret==0.4.7",
    "uri-template==1.3.0",
    "webcolors==24.11.1",
    "xlsxwriter==3.2.9",
]

[dependency-groups]
dev = [
    "ruff>=0.14.1",
    "ty>=0.0.1a25",
]
